---
# Users should edit this file
# Format of this file http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data


# Password for user pi
PI_USER_PASSWORD: "raspberry"

# Keyboard layout
RASPIAN_KEYBOARD_LAYOUT: "us"

# WIFI
RASPBIAN_OVERRIDE_WIFI_SETTINGS: false
RASPBIAN_WIFI_SSID: "MelbPC-NUE"
RASPBIAN_WIFI_PASSWORD: "peachspeak38"

# apt-get install software packages
RASPBIAN_APT_INSTALL:
  - arduino
  - audacity
  - vlc

# install node-red modules
NODERED_MODULES: 
  - node-red-dashboard
  - node-red-node-arduino
  - node-red-contrib-sms-telstra
  - node-red-contrib-influxdb





