---
# Users should edit this file
# Format of this file http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data

# Hostname for Pi
PI_HOSTNAME: "raspberry"

# Password for user pi
PI_USER_PASSWORD: "raspberry"

# Keyboard layout
RASPBIAN_KEYBOARD_LAYOUT: "us"

# WIFI
RASPBIAN_OVERRIDE_WIFI_SETTINGS: false
RASPBIAN_WIFI_SSID: "MelbPC-NUE"
RASPBIAN_WIFI_PASSWORD: "peachspeak38"

# Bluetooth LE
RASPBIAN_ENABLE_BLUETOOTH: true

# raspi-config interface settings

RASPICONFIG:
  SERIAL: true
  CAMERA: false
  VNC: true
  SPI: false
  I2C: false
  ONEWIRE: false
  RGPIO: false

# apt-get install software packages
RASPBIAN_APT_INSTALL:
  - camorama
  - influxdb-client

# install node-red modules
NODERED_MODULES: 
  - node-red-dashboard
  - node-red-node-arduino
  - node-red-contrib-sms-telstra
  - node-red-contrib-influxdb
  - node-red-contrib-redis

# Python
PYTHON_INSTALL_MODULES: true

# Python 2 modules available via apt-get install
PYTHON2_APT_MODULES:
  - python-easygui
  - python-bottle
  - python-dev

# Python 2 modules via pip
PYTHON2_PIP_MODULES:
  - pip
  - setuptools

# Python 3 modules available via apt-get
PYTHON3_APT_MODULES:
  - python3-dev

# Python 3 modules via pip
PYTHON3_PIP_MODULES:
  - pip
  - setuptools

# Install and configure ngrok
ENABLE_NGROK: false

# Install and configure docker
ENABLE_DOCKER: true

DOCKER:
  WEB: true
  PORTAINER: true
  SAMBA: true
  MQTT: true
  INFLUXDB: true
  HOMEASSISTANT: false
  HOMEASSISTANT_APPDAEMON: false
  OPENHAB: false
  MONGODB: false
  JUPYTER: true
  REDIS: false
  NODERED: false
  GRAFANA: false

MISCELLANEOUS:
  RETROPIE: false
  MOTIONEYE: false
  FUZEBASIC: false
  WORDPRESS: false
  
NGROK:
  TWITTER: false
  EMAIL: false













