---
- name: Install Amazon Alexa sample app for Pi
  hosts: raspberrypis
  tasks:
  #  - name: include vars
  #    include_vars:
  #      file: group_vars/raspberrypis.yml
  #    tags:
  #      - debug
  #  - name: print debug
  #    debug: 
  #      msg: "{{ msg }}"
  #    vars:
  #      msg: "{{ ALEXA.CLIENT_ID }}"      
  #    tags:
  #      - debug

    - name: Create alexa directory on Desktop
      file:
        name: "~/Desktop/alexa"
        state: directory

    - name: Download alexa
      shell: "wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/config.txt && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh"
      args:
        chdir: "~/Desktop/alexa"


    - name: Update client_id config.txt
      lineinfile:
        path: "~/Desktop/alexa/config.txt"
        regexp: "^CLIENT_ID="
        replace: "CLIENT_ID={{ ALEXA.CLIENT_ID }}"
        
    - name: Update product_id in config.txt
      lineinfile:
        path: "~/Desktop/alexa/config.txt"
        regexp: "^PRODUCT_ID="
        replace: "PRODUCT_ID={{ ALEXA.PRODUCT_ID }}"

    - name: Install alexa
      become: true
      shell: bash setup.sh config.txt
      args:
        chdir: "~/Desktop/alexa"
