---
- name: Install and update software through apt
  hosts: raspberrypis
  become: true
  tasks:
    - name: Install software
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - at-spi2-core
        - florence   
        - build-essential 

    - name: Install software from group_vars/raspberrypis.yml
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ RASPBIAN_APT_INSTALL }}"

  

  

 
