---
- name: Install and update software through apt
  hosts: raspberrypis
  tasks:
    - name: Get latest Raspbian updates
      apt: 
        update_cache: yes
      become: true

    - name: Make sure there are no broken packages
      command: apt-get -y -f install
      become: true 

    - name: Install software
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - arduino
        - audacity
        - vlc
        - at-spi2-core
        - florence 
        - realvnc-vnc-server  
        - build-essential  
      become: true

    - name: Install grafana
      apt:
        deb: https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.2.0/grafana_4.2.0_armhf.deb
      become: true
      



  

 
