---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Install docker
      shell: "curl -fsSL https://get.docker.com/ | bash"
      
    - name: Copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777        

    #- name: Download docker deb
    #  shell: wget --no-check-certificate -O /storage/docker/docker/docker-engine_17.05.0~ce-0~raspbian-jessie_armhf.deb https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_17.05.0~ce-0~raspbian-jessie_armhf.deb
    #  tags:
    #    - hack

    #- name: Install docker
    #  shell: dpkg -i docker-engine_17.05.0~ce-0~raspbian-jessie_armhf.deb
    #  args:
    #    chdir: /storage/docker/docker

    - name: Check docker status
      shell: /usr/bin/env docker version




    #- name: Start docker containers
    #  docker_service:
    #    project_src: /storage/docker
    #    state: present
    #    pull: yes
    #  retries: 3
    #  delay: 3
    #  register: result
    #  until: result.rc|succeeded
    #  tags:
    #    - startcontainers

    - name: Install docker-compose
      apt:
        name: docker-compose

    - name: Start docker containers
      shell: bash /storage/docker/docker/dockercomposescript.sh
      args:
        chdir: /storage/docker
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0
      tags:
        - startcontainers

    - name: Copy docker systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockerhack.service
        dest: /etc/systemd/system
      tags:
        - dockercomposeservice

    - name: Enable docker-hack systemd service
      systemd:
        name: dockerhack
        enabled: yes
      tags:
        - hack

    - name: Copy docker-compose systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockercompose.service
        dest: /etc/systemd/system
      tags:
        - dockercompose

    - name: Enable docker-compose systemd service
      systemd:
        name: dockercompose
        enabled: yes
      tags:
        - hack
