version: '2'
services:
  web:
    image: tmb28054/rpi-apache-php
    container_name: apache
    ports:
      - 8000:80
    volumes:
      - /storage/docker/webserver/html:/var/www/html

  portainer:
    image: portainer/portainer:linux-arm
    container_name: portainer
    command: --no-auth
    ports:
      - 9000:9000 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  samba:
    container_name: samba
    image: dastrasmue/rpi-samba:v3
    network_mode: "host"
    ports: 
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    volumes:
      - /storage:/share
    command: ["-s", "public:/share/public:rw:", "-s", "docker:/share/docker:rw:"]
  
  nodered:
    container_name: nodered
    image: nodered/node-red-docker:rpi
    ports:
      - 1881:1880
    volumes:
      - /storage/docker/nodered:/data

  #jupyter:
  #  container_name: jupyter
  #  image: romilly/rpi-docker-tensorflow
  #  ports:
  #    - 8009:8009
  #    - 6006:6006
  #  volumes:
  #    - /storage/docker/jupyter/notebooks:/notebooks/myNotebooks
  #    - /storage/docker/jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py



  