---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: total hack
      shell: rm -rf /var/lib/apt/lists/*
      tags:
        - installdocker

    - name: Install docker
      shell: "curl -fsSL https://get.docker.com/ | bash"
      tags:
        - installdocker

    - name: Copy docker-compose.yml to pi
      template:
        src: docker-compose-complete-jinja.yml
        dest: /storage/docker/docker-compose.yml
        owner: nobody
        group: nogroup
        mode: 0777  
        force: yes 
      vars:
        dockerWeb: "{{ DOCKER_WEB }}"
        dockerPortainer: "{{ DOCKER_PORTAINER }}"
        dockerSAMBA: "{{ DOCKER_SAMBA }}"
        dockerHomeAssistant: "{{ DOCKER_HOMEASSISTANT }}"
        dockerHomeAssistantAppDaemon: "{{ DOCKER_HOMEASSISTANT_APPDAEMON }}"
        dockerOpenHAB: "{{ DOCKER_OPENHAB }}"
        dockerMQTT: "{{ DOCKER_MQTT }}"
        dockerInfluxDB: "{{ DOCKER_INFLUXDB }}"
        dockerMongoDB: "{{ DOCKER_MONGODB }}"
        dockerJupyter: "{{ DOCKER_JUPYTER }}"
        dockerRedis: "{{ DOCKER_REDIS }}"
        dockerPostgres: "{{ DOCKER_POSTGRES }}"
        dockerNodeRed: "{{ DOCKER_NODERED }}"
      tags:
        - dockercomposeconfig

    - name: Copy kitchen sink docker-compose.yml to pi
      template:
        src: docker-compose-complete-jinja.yml
        dest: /storage/docker/docker-compose-kitchensink.yml
        owner: nobody
        group: nogroup
        mode: 0777  
        force: yes 
      vars:
        dockerWeb: true
        dockerPortainer: true
        dockerSAMBA: true
        dockerHomeAssistant: true
        dockerHomeAssistantAppDaemon: true
        dockerOpenHAB: true
        dockerMQTT: true
        dockerInfluxDB: true
        dockerMongoDB: true
        dockerJupyter: true
        dockerRedis: true
        dockerPostgres: true
        dockerNodeRed: true

      tags:
        - dockercomposeconfig

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Install docker-compose
      apt:
        name: docker-compose

    - name: Start docker containers (could take 30min)
      shell: bash /storage/docker/docker/dockercomposescript.sh
      args:
        chdir: /storage/docker
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0
      tags:
        - startcontainers

    - name: Copy docker systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockerhack.service
        dest: /etc/systemd/system
      tags:
        - dockerservices

    - name: Enable docker-hack systemd service
      systemd:
        name: dockerhack
        enabled: yes
      tags:
        - hack
        - dockerservices

    - name: Copy docker-compose systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockercompose.service
        dest: /etc/systemd/system
      tags:
        - dockercompose
        - dockerservices

    - name: Enable docker-compose systemd service
      systemd:
        name: dockercompose
        enabled: yes
      tags:
        - hack
        - dockerservices
