---
- name: Install docker containers using docker compose
  hosts: raspberrypis
  become: true
  tasks:
    - name: Copy docker-compose.yml file
      copy:
        src: docker-compose.yml
        dest: /storage/docker
    - name: Install docker containers via docker compose
      docker_service:
        project_src: /storage/docker
