---
- name: Install docker Ansible prerequisite on control ubuntu PC
  hosts: localhost
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{item}}"
      with_items:
        - python-pip
          
    - name: Install python docker
      pip:
        name: "{{item}}"
        version: "1.9.0"
        state: forcereinstall
      with_items:
        - docker-py
        - docker-compose

    - name: Install pyyaml
      pip:
        name: pyYAML

- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Prerequisite for installing docker on raspberrypis
      apt:
        name: lsb-release
        state: latest

    - name: Install docker
      shell: curl -fsSL https://get.docker.com | sh

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: latest

    - name: Copy docker-compose to pi
      copy:
        src: docker-compose.yml
        dest: /root
      tags:
        - dockercompose

    - name: Allow guest access to samba share
      file:
        path: /storage
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/public folder
      file:
        path: /storage/public
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/docker directory
      file:
        path: /storage/docker
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: Copy docker-compose to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777        
      tags:
        - dockercompose

    - name: Copy files
      copy:
        src: files/
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777
      tags:
        - dockercompose

    - name: phpmyadmin permission issue
      file:
        path: /storage/docker/phpmyadmin/config.inc.php
        mode: 0774

    - name: Copy docker-compose systemd service
      copy:
        src: files/docker/docker-compose.service
        dest: /etc/systemd/system

    - name: Enable docker-compose systemd service
      systemd:
        name: docker-compose
        enabled: yes
        state: started

# - name: Install docker containers via docker compose
#  docker_service:
#    project_src: /storage/docker
#  tags:
#    - dockercompose
#    - startdockercontainers



