---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Copy docker install script
      copy:
        src: files/apt-docker/get-docker.sh
        dest: /tmp/get-docker.sh
        mode: 0777

    - name: Run docker install script
      command: /tmp/get-docker.sh

    #- name: remove docker install script
    #  file:
    #    path: /tmp/get-docker.sh
    #    state: absent

    - name: Allow guest access to samba share
      file:
        path: /storage
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/public folder
      file:
        path: /storage/public
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/docker directory
      file:
        path: /storage/docker
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: Copy files
      copy:
        src: files/
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777
      tags:
        - dockercompose

    - name: Copy docker services
      copy:
        src: files/docker/docker.service
        dest: /etc/systemd/system    

    - name: Enable docker systemd service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Install docker-compose
      pip: 
        name: docker-compose

    - name: copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
      tags:
        - startcontainers

    - name: run dockercomposescript
      shell: bash /storage/docker/docker/dockercomposescript.sh


  



     