---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Install docker
      shell: "curl -sSL https://get.docker.com/ | sudo bash"

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777        


    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Start docker containers
      shell: docker-compose up -d
      args:
        chdir: /storage/docker


    #- name: Enable docker-compose systemd service
    #  systemd:
    #    name: docker-compose
    #    enabled: yes




