---
- name: Install docker Ansible prerequisite on control ubuntu PC
  hosts: localhost
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{item}}"
      with_items:
        - python-pip
        - docker-compose
    
    - name: Install pyyaml
      pip:
        name: PyYAML

- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Prerequisite for installing docker on raspberrypis
      apt:
        name: lsb-release
        state: latest

    - name: install python docker module
      pip:
        name: "{{item}}"
      with_items:
        - docker
        - "docker-compose"
      tags:
        - dockercompose

    - name: Install Docker
      shell: "curl -sSL https://get.docker.com | bash"
      register: output

    - name: Debug output
      debug:
        msg: "{{output.stdout_lines}}"

    - name: Copy docker-compose to pi
      copy:
        src: docker-compose.yml
        dest: /root
      tags:
        - dockercompose

    - name: Allow guest access to samba share
      file:
        path: /storage
        state: directory
        owner: pi
        group: pi
        mode: 0777
        recurse: yes

    - name: create /storage/public folder
      file:
        path: /storage/public
        state: directory
        owner: pi
        group: pi
        mode: 0777

    - name: create /storage/docker directory
      file:
        path: /storage/docker
        state: directory
        owner: pi
        group: pi
        mode: 0777

    - name: Copy files
      copy:
        src: files/
        dest: /storage/docker
        owner: nobody
        group: nogroup
      tags:
        - dockercompose

    - name: Copy docker-compose systemd service
      copy:
        src: files/docker/docker-compose.service
        dest: /etc/systemd/system

    - name: move README.txt to /storage folder
      copy:
        src: /storage/docker/samba/README.txt
        dest: /storage/docker
        remote_src: True
        mode: 0777

    - name: Enable docker-compose systemd service on boot
      systemd:
        name: docker-compose
        enabled: yes

    - name: Install docker containers via docker compose
      docker_service:
        project_src: /root
      tags:
        - dockercompose


