---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    #- name: Copy docker install script
    #  copy:
    #    src: files/apt-docker/get-docker.sh
    #    dest: /tmp/get-docker.sh
    #    mode: 0777

    #- name: Run docker install script
    #  command: /tmp/get-docker.sh

    #- name: remove docker install script
    #  file:
    #    path: /tmp/get-docker.sh
    #    state: absent


    # Hack required (on boot, must reinstall docker 
    # by doing dpkg -i docker-ce_17.09.0~ce-0~raspbian_armhf.deb)
    - name: Install docker
      shell: "wget -O /storage/docker/docker-ce_17.09.0~ce-0~raspbian_armhf.deb https://download.docker.com/linux/raspbian/dists/stretch/pool/edge/armhf/docker-ce_17.09.0~ce-0~raspbian_armhf.deb && cd /storage/docker  && dpkg -i docker-ce_17.09.0~ce-0~raspbian_armhf.deb"  

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
      tags:
        - dockercompose

    - name: Install docker containers
      docker_service:
        project_src: /storage/docker

    #- name: Start docker containers
    #  shell: "docker-compose up -d"
    #  args:
    #    chdir: /storage/docker
    #  tags:
    #    - dockercompose
    #  retries: 3
    #  delay: 5
    #  register: result
    #  until: result.rc == 0

    - name: Copy docker systemd files
      copy:
        remote_src: yes
        src: "{{item}}"
        dest: /etc/systemd/system
      with_items:
        - /storage/docker/docker/dockerhack.service
        - /storage/docker/docker/dockercompose.service
      tags:
        - dockercomposeservice
      
    - name: Docker Hack systemd
      systemd:
        name: dockerhack
        enabled: yes
      tags:
        - dockercomposeservice

    - name: Docker compose systemd
      systemd:
        name: dockercompose
        enabled: yes
      tags:
        - dockercomposeservice





    #- name: run dockercomposescript
    #  shell: bash /storage/docker/docker/dockercomposescript.sh

  



     