---
- name: Jupyter and tensorflow and Julia
  hosts: raspberrypis
  become: true
  tasks:
    - name: Fix broken packages
      shell: apt-get -y -f install

    - name: Install Julia
      apt: 
        name: "{{item}}"
      with_items:
        - julia
        - libzmq3-dev
        - python3-zmq
        - "r-base"
        - "libssl-dev"
        - "python-seaborn" 
        - "python-pandas"
        - "python-matplotlib"
        - "ttf-bitstream-vera"
      retries: 2
      register: result
      until: result|succeeded
      ignore_errors: yes

    - name: Install Jupyter on Python 2
      pip:
        name: jupyter

    - name: Install Jupyter on Python 3
      pip:
        executable: pip3
        name: jupyter

    - name: remove julia
      apt:
        name: julia
        state: absent
      tags:
        - hack

    - name: install julia
      apt:
        name: julia
      tags:
        - hack

    - name: Install IJulia
      shell: |
        julia -e 'Pkg.add("IJulia");'

    - name: Copy systemd for jupyter-notebook
      copy:
        src: files/systemd/jupyter.service
        dest: /etc/systemd/system

    - name: create notebooks directory
      file:
        path: /storage/docker/jupyter/notebooks
        mode: 0777
        state: directory

    - name: start and enable jupyter
      systemd:
        name: jupyter
        enabled: yes
        state: started

    - name: Install Ipython for Python 2
      apt:
        name: python-ipykernel
      retries: 2
      register: result
      until: result|succeeded
      ignore_errors: yes

    - name: Install tensorflow
      shell: pip install https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.1.0/tensorflow-1.1.0-cp27-none-linux_armv7l.whl


    - name: Install Ipython2 kernel
      shell: ipython kernel install --user

    - name: Install Ipython3 kernel
      shell: ipython3 kernel install --user

    - name: Install bash_jupyter
      pip:
        name: bash_kernel

    - name: Install bash_kernel kernelspec
      shell: python -m bash_kernel.install 












