---
- name: Change keyboard layout to US
  hosts: raspberrypis 
  tasks:    
    - name: Download script to change keyboard layout
      get_url:
        url: 'https://gist.githubusercontent.com/raspberrypisig/b92d3ab92a51d74b857da9bc02958d56/raw/004f2609f40e848d127b66edd8b69b210727a945/setupKeyboardonPi.sh'
        dest: /tmp/setupKeyboard.sh
        mode: 0555

    - name: Delete a line in the file
      lineinfile:
        regexp: "^sudo debconf-set-selections <<< 'console-data console-data/keymap/policy select Select keymap from full list'"
        line: ""
        path: /tmp/setupKeyboard.sh

    - name: debconf settings
      debconf:
        name: console-data
        question: console-data/keymap/policy
        value: "Select keymap from full list"
        vtype: select
      become: true
    
    - name: Run keyboard layout change script
      shell: /tmp/setupKeyboard.sh
      become: true
