---
- name: Change keyboard layout to US
  hosts: raspberrypis 
  tasks:    
    - name: Copy setupkeyboard.sh to pi
      copy:
        src: setupkeyboard.sh
        dest: /tmp/setupkeyboard.sh

    - name: debconf settings
      debconf:
        name: console-data
        question: console-data/keymap/policy
        value: "Select keymap from full list"
        vtype: select
      become: true
    
    - name: Run keyboard layout change script
      command: bash /tmp/setupkeyboard.sh
      become: true


