---
- name: Install LAMP(Apache, MySQL, PHP)
  hosts: raspberrypis
  vars:
    php_packages:
      - libapache2-mod-php5
      - php5-mysql
  roles:
    - geerlingguy.apache
    - geerlingguy.php    
    - geerlingguy.mysql
  become: true

- name: Copy index.html to /var/www/html
  hosts: raspberrypis
  become: true
  tasks:
    - name: Copy index.html to /var/www/html
      copy:
        src: index.html
        dest: /var/www/html





