---
- name: Install nginx as a reverse proxy to be used in conjection with ngrok to access http-based applications over the internet
  hosts: raspberrypis
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx 

    - name: Remove nginx default file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Copy nginx.conf
      copy:
        src: files/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Start and enable nginx
      systemd:
        name: nginx
        enabled: yes
        state: restarted
