---
- name: Install ngrok
  hosts: raspberrypis
  become: true
  tasks:
    - name: Download and install nkgrok 
      unarchive:
        src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
        remote_src: true
        dest: /usr/local/bin








