---
- name: Upgrade nodejs and npm to latest
  hosts: raspberrypis
  tasks:
    #- name: Install node-red
    #  become: yes
    #  apt:
    #    name: "{{item}}"
    #  with_items:
    #    - nodered
    #    - npm

    #- name: Remove lists for stretch
    #  shell: "rm -rf /var/lib/apt/lists/*"
    #  become: yes

    - name: Download update-nodejs-and-nodered
      get_url:
        url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered
        dest: /tmp/update-nodejs-and-nodered
        mode: 0777

    - name: Upgrade nodejs and nodered
      shell: "yes|/tmp/update-nodejs-and-nodered"

    - name: start and enable nodered service
      systemd:
        name: nodered
        enabled: yes
        state: started
      become: yes    

    - name: Install node-red modules
      npm: 
        name: "{{ item }}"
        path: /home/pi/.node-red
      with_items: "{{ NODERED_MODULES }}"


