---
- name: Upgrade nodejs and npm to latest
  hosts: raspberrypis
  tasks:
    #- name: Install node-red
    #  become: yes
    #  apt:
    #    name: "{{item}}"
    #  with_items:
    #    - nodered
    #    - npm

    #- name: Remove lists for stretch
    #  shell: "rm -rf /var/lib/apt/lists/*"
    #  become: yes

    - name: Download update-nodejs-and-nodered
      get_url:
        url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered
        dest: /tmp/update-nodejs-and-nodered
        mode: 0777

    - name: Upgrade nodejs and nodered
      shell: "yes|/tmp/update-nodejs-and-nodered"

   

    #- name: Install node-red modules
    #  shell: npm install {{ item }}
    #  args:
    #    chdir: /home/pi/.node-red
    #  tags:
    #    - noderedmodules
    #  with_items: "{{ NODERED_MODULES }}"

    - name: Upgrade nodejs
      shell: "curl -sL https://deb.nodesource.com/setup_6.x | bash -"
      become: true

    - name: Remove old nodered
      shell: "apt-get purge -y --remove nodejs"
      become: true

    - name: apt clean
      shell: "apt-get clean"
      become: true

    - name: apt update
      shell: "apt-get update"
      become: true

    - name: Install nodered
      shell: "apt-get install -y nodejs"
      become: true    

    - name: Install node-red modules
      npm: 
        name: "{{ item }}"
        path: /home/pi/.node-red
      with_items: "{{ NODERED_MODULES }}"

    - name: start and enable nodered service
      systemd:
        name: nodered
        enabled: yes
        state: started
      become: true