---
# If you see {{SOME_VARIABLE}} in the yml files, these are 
# Ansible variables, defined in the group_vars directory 

- name: Install prerequisites on controlling computer
  import_playbook: prerequisites.yml
  tags:
    - prerequisites

- name: Update raspbian package list
  import_playbook: apt-update.yml
  tags:
    - aptupdate

- name: Install Apt Software
  import_playbook: apt-software.yml
  tags:
    - apt

- name: Raspbian Setup
  import_playbook: raspbian-setup.yml
  tags: raspbiansetup

- name: Keyboard Layout
  import_playbook: keyboard-layout.yml
  tags:
    - keyboard

- name: NodeRED
  import_playbook: node-red-better-upgrade-method.yml
  tags:
    - nodered

- name: Python
  import_playbook: python.yml
  tags:
    - python

- name: SAMBA
  import_playbook: sambafiles.yml
  tags:
    - samba

- name: Docker
  import_playbook: docker-simple.yml
  tags:
    - dockersimple
  when: ENABLE_DOCKER

- name: ngrok
  import_playbook: ngrok.yml
  tags:
    - ngrok
  when: ENABLE_NGROK

