---
# If you see {{SOME_VARIABLE}} in the yml files, these are 
# Ansible variables, defined in the group_vars directory 

- include: prerequisites.yml
  tags:
    - prerequisites

- include: apt-software.yml
  tags:
    - apt

- include: raspbian-setup.yml
  tags: raspbiansetup

- include: keyboard-layout.yml
  tags:
    - keyboard

- include: node-red-better-upgrade-method.yml
  tags:
    - nodered

- include: python.yml
  tags:
    - python

- include: amazon-alexa.yml
  tags:
    - voice
    - alexa

- include: google-assistant.yml
  tags:
    - voice
    - googleassistant

- include: nginx.yml
  tags:
    - nginx

- include: sambafiles.yml
  tags:
    - samba

- include: pip.yml
  tags:
    - pip

- include: dockerexperimental.yml
  tags:
    - docker

- include: jupyter.yml
  tags:
    - jupyter

- include: ngrok.yml
  tags:
    - ngrok