---
# If you see {{SOME_VARIABLE}} in the yml files, these are 
# Ansible variables, defined in the group_vars directory 

- import_playbook: prerequisites.yml
  tags:
    - prerequisites

- import_playbook: apt-software.yml
  tags:
    - apt

- import_playbook: raspbian-setup.yml
  tags: raspbiansetup

- import_playbook: keyboard-layout.yml
  tags:
    - keyboard

- import_playbook: node-red-better-upgrade-method.yml
  tags:
    - nodered

- import_playbook: python.yml
  tags:
    - python

- import_playbook: amazon-alexa.yml
  tags:
    - voice
    - alexa

- import_playbook: google-assistant.yml
  tags:
    - voice
    - googleassistant

#- import_playbook: nginx.yml
#  tags:
#   - nginx

- import_playbook: sambafiles.yml
  tags:
    - samba

#- import_playbook: pip.yml
#  tags:
#    - pip



- import_playbook: ngrok.yml
  tags:
    - ngrok

- import_playbook: jupyter.yml
  tags:
    - jupyter

- import_playbook: docker.yml
  tags:
    - docker
