---
- name: Raspberry Pi Basic Settings
  hosts: raspberrypis
  become: true
  tasks:
    - name: Rename hostname
      shell: 'echo {{inventory_hostname}} > /etc/hostname'

    - name: Change password for user pi
      shell: 'echo pi:{{PI_USER_PASSWORD}} | chpasswd'

    - name: Disable bluetooth LE
      systemd:
        name: bluetooth
        enabled: no
        state: stopped

      when: not RASPBIAN_ENABLE_BLUETOOTH
      tags:
        - bluetooth

    - name: Enable bluetooth LE
      systemd:
        name: bluetooth
        enabled: yes
        state: started
      when: RASPBIAN_ENABLE_BLUETOOTH
      tags:
        -bluetooth

    - name: Setup wifi
      copy:
        src: wpa_supplicant.conf
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
      when: RASPBIAN_OVERRIDE_WIFI_SETTINGS

    - name: Set raspiconfig variable
      set_fact: 
        raspiconfig: "{{ RASPICONFIG }}"

    - name: Enable serial
      shell: "raspi-config nonint do_serial 0"
      when: "{{ raspiconfig.SERIAL }}"

    - name: Enable I2C
      shell: "raspi-config nonint do_i2c 0"
      when: "{{ raspiconfig.I2C }}"

    - name: Enable SPI
      shell: "raspi-config nonint do_spi 0"
      when: "{{ raspiconfig.SPI }}"

    - name: Enable Camera
      shell: "raspi-config nonint do_camera 0"
      when: "{{ raspiconfig.CAMERA }}"

    - name: Enable VNC
      shell: "raspi-config nonint do_vnc 0"
      when: "{{ raspiconfig.VNC }}"

    - name: Enable OneWire
      shell: "raspi-config nonint do_onewire 0"
      when: "{{ raspiconfig.ONEWIRE }}"

    - name: Enable Remote GPIO
      shell: "raspi-config nonint do_rgpio 0"
      when: "{{ raspiconfig.RGPIO }}"

    - name: Disable serial
      shell: "raspi-config nonint do_serial 1"
      when: "not {{ raspiconfig.SERIAL }}"

    - name: Disable I2C
      shell: "raspi-config nonint do_i2c 1"
      when: "not {{ RASPICONFIG_ENABLE_I2C }}"

    - name: Disable SPI
      shell: "raspi-config nonint do_spi 1"
      when: "not {{ RASPICONFIG_ENABLE_SPI }}"

    - name: Disable Camera
      shell: "raspi-config nonint do_camera 1"
      when: "not {{ RASPICONFIG_ENABLE_CAMERA }}"

    - name: Disable VNC
      shell: "raspi-config nonint do_vnc 1"
      when: "not {{ RASPICONFIG_ENABLE_VNC }}"

    - name: Disable OneWire
      shell: "raspi-config nonint do_onewire 1"
      when: "not {{ RASPICONFIG_ENABLE_ONEWIRE }}"

    - name: Disable Remote GPIO
      shell: "raspi-config nonint do_rgpio 1"
      when: "not {{ RASPICONFIG_ENABLE_RGPIO }}"






  