---
- name: Samba /storage folder
  hosts: raspberrypis
  become: true
  tasks:
    - name: Allow guest access to samba share
      file:
        path: /storage
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/public folder
      file:
        path: /storage/public
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/docker directory
      file:
        path: /storage/docker
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: Copy files
      copy:
        src: files/
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777
  



     