---
- name: Install OpenCV 3.2.0
  hosts: raspberrypis
  tasks:
    - name: Update apt repos
      apt:
        update_cache: yes
      become: true

    - name: install prereqs
      apt:
        name: "{{ item }}"
      become: true
      with_items:
        - build-essential
        - cmake
        - cmake-curses-gui
        - pkg-config
        - libjpeg-dev
        - libtiff5-dev
        - libjasper-dev
        - libpng12-dev
        - libavformat-dev
        - libswscale-dev
        - libeigen3-dev
        - libxvidcore-dev
        - libx264-dev
        - libgtk2.0-dev
        - libv4l-dev
        - v4l-utils
        - libatlas-base-dev 
        - gfortran
        - python2.7-dev 
        - python2.7-numpy
        - python3-dev 
        - python3-numpy
        - tesseract-ocr 
        - libtesseract-dev 
        - libleptonica-dev

    - name: Enable v4l module
      modprobe:
        name: bcm2835-v4l2
      become: true

    - name: create directory for opencv
      file:
        path: /home/pi/opencv
        state: directory

    - name: Download opencv 
      unarchive:
        src: https://github.com/opencv/opencv/archive/3.2.0.zip
        dest: /home/pi/opencv 
        remote_src: True

    - name: Download opencv-contrib
      unarchive:
        src: https://github.com/opencv/opencv_contrib/archive/3.2.0.zip
        dest: /home/pi/opencv
        remote_src: True

    - name: create directory for building opencv
      file:
        path: /home/pi/opencv/opencv-3.2.0/build
        state: directory

    - name: cmake
      shell: |
        cd /home/pi/opencv/opencv-3.2.0/build
        cmake -D CMAKE_BUILD_TYPE=RELEASE \
              -D CMAKE_INSTALL_PREFIX=/usr/local \
              -D BUILD_WITH_DEBUG_INFO=OFF \
              -D BUILD_DOCS=OFF \
              -D BUILD_EXAMPLES=OFF \
              -D BUILD_TESTS=OFF \
              -D BUILD_opencv_ts=OFF \
              -D BUILD_PERF_TESTS=OFF \
              -D INSTALL_C_EXAMPLES=ON \
              -D INSTALL_PYTHON_EXAMPLES=ON \
              -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.2.0/modules \
              -D ENABLE_NEON=ON \
              -D WITH_LIBV4L=ON \
              ../

    - name: Install OpenCV
      shell: |
        make -j2
        make install
        ldconfig
      args:
        chdir: /home/pi/opencv/opencv-3.2.0/build
      become: true
      tags:
        - cmake














